const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_REQUEST = "NEW_REQUEST";
const ONLINE_USERS = "ONLINE_USERS";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

export {
    ALERT,
    REFETCH_CHATS,
    NEW_ATTACHMENT,
    NEW_MESSAGE_ALERT,
    NEW_MESSAGE,
    NEW_REQUEST,
    ONLINE_USERS,
    START_TYPING,
    STOP_TYPING
};
